### ISSUE TITLE
Why TRTA is not allowed to be missing in ADSL?

### ISSUE THREAD

**Issue by yuliasidi** [Merck/forestly#15]
In general,  ADSL.TRTA could be missing for screening failures, however the below code generates an error. Could you please advise if this is the intended behavior?

```r
library(forestly)

forestly_adsl_mod <- forestly_adsl |>
  dplyr::mutate(
    TRT01A = ifelse(USUBJID == "01-718-1355", "", TRT01A),
    TRTA = factor(TRT01A, levels = c("Xanomeline Low Dose", "Placebo"), labels = c("Low Dose", "Placebo"))
  )

forestly_adae_mod <- forestly_adae |>
  dplyr::filter(USUBJID != "01-718-1355")


forestly::meta_forestly(
  dataset_adsl = forestly_adsl_mod,
  dataset_adae = forestly_adae_mod,
  population_term = "apat",
  population_subset = SAFFL == "Y",
  observation_term = "wk12",
) |>
  prepare_ae_forestly(parameter = "any;rel")
```

**Comment by elong0527** [comment]
Yeah, we designed to require treatment group is not missing to avoid accidentally remove records accidentally. 

If you really need to compare "Missing" as a group, you can explicitly define a group at data manipulation stage. 

e.g. 

```
  TRTA = factor(TRT01A, levels = c("Xanomeline Low Dose", "Placebo", NA), labels = c("Low Dose", "Placebo", "Missing"), exclude = NULL)
```

**Comment by yuliasidi** [comment]
Thank you, Yilong. 
The missing category was not of interest in this case. It was just confusing to receive this error message given the `population_subset = SAFFL == "Y"` argument specification.
I understand the logic of not allowing missing TRTA variable, however, in practice ADSL could have missing TRTA (either due to screen failures, or patients who were randomized and not treated). Would it be possible to consider the treatment variable based on the `population_subset`, please?

**Comment by elong0527** [comment]
Would it solve the problem if we add an additional argument in `meta_forestly` to allow user specify treatment group? 

The `meta_forestly` is a wrapper of the `metalite` functions https://github.com/Merck/forestly/blob/main/R/meta_forestly.R

**Comment by yuliasidi** [comment]
Yes, I think it would be helpful to have treatment arm as an argument in `meta_forestly()`. 

But it looks like the error in the above example is generating when applying `forestly::prepare_ae_forestly()`, specifically from `metalite.ae::prepare_ae_specific()` step. Wouldn't it make sense to specify the subsetted treatment in the meta data so that the treatment arm doesn't show up as missing when the subsetting condition is applied?

**Comment by elong0527** [comment]
An error message from `forestly::prepare_ae_forestly()` actually infer issues in its dependency input `metalite` object defined in `meta_forestly`.

The design of `forestly` is to leverage `metalite` to define input information with a wrap up `meta_forestly` function. `meta_forestly` only contain limited input to reduce learning curve for new users. 

Define `metalite` object provide more flexibility to advanced user https://merck.github.io/forestly/articles/forestly.html#define-metadata

**Comment by yuliasidi** [comment]
Thank you for the response.
Based on the example from `metalite`, if `population`  argument in the `metalite::meta_adam()` has a missing treatment then even though `metalite::define_population()` defines the correct subsetting, e.g., `SAFFL == "Y"` (for which treatment is available for all the patients), the following error is still generated:
`Error: There are >= 1 subjects with missing grouping variable 'TRT01A' in the population dataset.`
Currently, in order to omit this error, I am filtering the adsl dataset upfront for `SAFFL == "Y"`. But I am not sure if it makes sense to have such data pre-processing step as part of the workflow. 
Further thoughts?

**Comment by elong0527** [comment]
I would keep the error as is to be conservative for clinical data analysis. 

If a subset condition result in missing treatment group, I suspect the likelihood of having data issue is high. 

The consequence is worse if a user run an analysis without checking missing values in `TRT01A`.

If you really want to avoid missing values without the filter step for a dataset, you may try `SAFFL == "Y" & (! is.na(TRT01A))`. And the condition will be the actual subset condition to be provided in the analysis specification if you follow https://merck.github.io/metalite/articles/ar-grid.html

**Comment by yuliasidi** [comment]
Thanks, Yilong and Happy New Year! I missed a step in the initial code example I provided in the issue, please see below. In this case patient `"01-718-1355"` is not in SAFFL population, but there is still an error. 
`forestly_adsl_mod <- forestly_adsl |>
  dplyr::mutate(
    TRT01A = ifelse(USUBJID == "01-718-1355", "", TRT01A),
    SAFFL =  ifelse(USUBJID == "01-718-1355", "", SAFFL),
    TRTA = factor(TRT01A, levels = c("Xanomeline Low Dose", "Placebo"), labels = c("Low Dose", "Placebo"))
  )

forestly_adae_mod <- forestly_adae |>
  dplyr::filter(USUBJID != "01-718-1355")


forestly::meta_forestly(
  dataset_adsl = forestly_adsl_mod,
  dataset_adae = forestly_adae_mod,
  population_term = "apat",
  population_subset = SAFFL == "Y",
  observation_term = "wk12",
) |>
  prepare_ae_forestly(parameter = "any;rel")`

**Comment by yuliasidi** [comment]
Hi @elong0527, following up on the above, please

**Comment by wangben718** [comment]
> Hi @elong0527, following up on the above, please

Hi @yuliasidi , the reason of this unexpected error message comes from missing value check in `metalite.ae` (https://github.com/Merck/metalite.ae/blob/84daec83c83026908c1b774a902af223e8abb77c/R/prepare_ae_specific.R#L71). I am going to change it to check missing value after population/observation dataset is filtered by `parameter` subset criteria.

**Comment by wangben718** [comment]
> Thanks, Yilong and Happy New Year! I missed a step in the initial code example I provided in the issue, please see below. In this case patient `"01-718-1355"` is not in SAFFL population, but there is still an error.
> 
> ```r
> forestly_adsl_mod <- forestly_adsl |>
>   dplyr::mutate(
>     TRT01A = ifelse(USUBJID == "01-718-1355", "", TRT01A),
>     SAFFL =  ifelse(USUBJID == "01-718-1355", "", SAFFL),
>     TRTA = factor(TRT01A, levels = c("Xanomeline Low Dose", "Placebo"), labels = c("Low Dose", "Placebo"))
>   )
> 
> forestly_adae_mod <- forestly_adae |>
>   dplyr::filter(USUBJID != "01-718-1355")
> 
> 
> forestly::meta_forestly(
>   dataset_adsl = forestly_adsl_mod,
>   dataset_adae = forestly_adae_mod,
>   population_term = "apat",
>   population_subset = SAFFL == "Y",
>   observation_term = "wk12",
> ) |>
>   prepare_ae_forestly(parameter = "any;rel")
> ```
Hi @yuliasidi ,
