### ISSUE TITLE
Is it possible to add more grade 3-5 parameter to the `forestly::prepare_ae_forestly`?

### ISSUE THREAD

**Issue by yuliasidi** [Merck/forestly#20]
In oncology it is common to present AEs with grade 3-5 toxicity level. Would it be possible to add an option like that to the list of the parameters available in `forestly::prepare_ae_forestly`, please? Also, it would be helpful to know what are the options in the documentation.

**Comment by elong0527** [comment]
We have `g35` keywords as defined in https://github.com/Merck/metalite/blob/main/data-raw/default_parameter_ae.R.

Example:

```
library(forestly)

forestly::meta_forestly(
  dataset_adsl = forestly_adsl,
  dataset_adae = forestly_adae |> dplyr::mutate(ATOXGRN = 3),
  population_term = "apat",
  population_subset = SAFFL == "Y",
  observation_term = "wk12",
  parameter_term = "any;rel;g35"
) |>
  forestly::prepare_ae_forestly(parameter = "any;rel;g35",
                                ae_listing_display = c("SITEID","AGE", "SEX", "RACE")) |>
  forestly::format_ae_forestly() |>
  forestly::ae_forestly()
 ```

If the default values does not meet your requirement. We define input metadata using the `metalite` package. To add additional parameter you can follow doc below by adding another `define_parameter` function. The `meta_forestly` is just a wrapper of these functions.

https://merck.github.io/forestly/articles/forestly.html#define-metadata

More details can be found in the `metalite` package https://merck.github.io/metalite/articles/metalite.html

I agree the information are not all in one place. Would you want to contribute a vignettes on this topic?

**Comment by yuliasidi** [comment]
Thank you, it worked for me. 
Just curious is it possible to pass the `parameter_term` from `forestly::meta_forestly` directly to  `forestly::prepare_ae_forestly`  `parameter `, instead of specifying it twice?
Happy to add a vignette. What do you have in mind? The connection between the metalite and forestly for the `forestly::meta_forestly`? 
Also, it could be helpful to have a similar documentation about the `parameter` in `metalite::plan()` as currently appears in the above vignette for `forestly`. What do you think?

**Comment by elong0527** [comment]
yes, we can make it as a default behavior to pass by all parameters as default. 

>The connection between the metalite and forestly for the forestly::meta_forestly?

Yes, that will be good. Information that can help new user reduce learner curve. 

>  Also, it could be helpful to have a similar documentation about the parameter in metalite::plan() as currently appears in the above vignette for forestly. What do you think?

We'd better to have one source of truth to reduce future maintainess efforts. We can add hyper links to refer the source if needed.

**Comment by yuliasidi** [comment]
I was trying to add another parameter to be presented in the forest plot using the below code, however, I am getting an error. Could you please let me know what I am doing wrong? Please note, I would like to add this as an example to the vignette I am adding.

```
meta_new <- meta_adam(
  population = forestly_adsl,
  observation = forestly_adae
  ) |>
  define_plan(plan = metalite::plan(
    analysis = "ae_forestly",
    population = "apat",
    observation = "wk12",
    parameter = "any;ser;g35;reduc"
    )
  ) |>
  define_population(
    name = "apat",
    group = "TRTA",
  ) |>
  define_observation(
    name = "wk12",
    group = "TRTA",
    label = "Weeks 0 to 24"
  ) |>
  define_parameter(
    name = "reduc",
    subset = AEACN == "DOSE REDUCED",
    label = "adverse events resulting in dose reduction"
  ) |>
  define_analysis(
    name = "ae_forestly",
    label = "Interactive forest plot"
  ) |>
  meta_build()

meta_new |>
  prepare_ae_forestly(parameter = "any;ser;g35;reduc") |>
  format_ae_forestly() |>
  ae_forestly()
```

**Comment by elong0527** [comment]
Here is a working example. The error message trying to tell user that the dataset contain some missing variables and the `define_parameter` require additional information as specified in https://github.com/Merck/metalite/blob/main/data-raw/default_parameter_ae.R 

```
library(dplyr)
library(metalite)
devtools::load_all()

tmp_adae <- forestly_adae %>% 
  mutate(
    TRTA = factor(TRTA, c("Xanomeline Low Dose", "Placebo")),
    ATOXGRN = rep(1:5, length.out = n()),
    AEACN = ifelse(1:n() %% 3 == 0, "DOSE REDUCED", AEACN)
  ) 
  

meta_new <- meta_adam(
  population = forestly_adsl,
  observation = tmp_adae
) |>
  define_plan(plan = metalite::plan(
    analysis = "ae_forestly",
    population = "apat",
    observation = "wk12",
    parameter = "any;ser;g35;reduc"
  )
  ) |>
  define_population(
    name = "apat",
    group = "TRTA",
  ) |>
  define_observation(
    name = "wk12",
    group = "TRTA",
    label = "Weeks 0 to 24"
  ) |>
  define_parameter(
    name = "reduc",
    label = "adverse events resulting in dose reduction",
    subset = AEACN == "DOSE REDUCED",
    var = "AEDECOD",
    soc = "AEBODSYS",
    seq = 900,
    term1 = "",
    term2 = "Result in Dose Reduction",
    summ_row = "dose reduction"
  ) |>
  define_analysis(
    name = "ae_forestly",
    label = "Interactive forest plot"
  ) |>
  meta_build()

meta_new |>
  prepare_ae_forestly(parameter = "reduc") |>
  format_ae_forestly() |>
  ae_forestly()
```

**Comment by yuliasidi** [comment]
@elong0527, sorry it took so long to get back to this. I am honestly a bit puzzled with the amount of information that is expected in the `define_parameter`.  For example in the above example, why isn't a user allowed to just set the following:
```
  define_parameter(
    name = "reduc",
    label = "adverse events resulting in dose reduction",
    subset = AEACN == "DOSE REDUCED"
  ) 
```

Would you consider simplifying the arguments that are mandatory in the `define_parameter()`? 
Also, please note that the current documentation for `define_parameter()` is very limited and it is difficult for a user who is not familiar with all the details of the metalite packages to figure out how to define a new parameter.

**Comment by elong0527** [comment]
The discussion of `reduc` has beyond the original issue in the title. 

Please create a new issue for the discussion.
