### ISSUE TITLE
Should `population_term` and `observation_term` be mandatory in `meta_forestly`?

### ISSUE THREAD

**Issue by yuliasidi** [Merck/forestly#43]
Since each forest plot is specified for a particular population/subset of observations - do the `population_term` and `observation_term` really need to be defined? The actual subsetting is already specified in `population_subset` and `observation_subset`, therefore, requiring a user to give these subsets names for generating one plot seems to be redundant. 

Please consider either removing these arguments or assigning some default values so users don't need to deal with the additional unnecessary parameters specification.

**Comment by elong0527** [comment]
Closed per #48
