### ISSUE TITLE
release v0.1.1

### ISSUE THREAD

**Issue by wangben718** [Merck/forestly#56]
First release

- [x] Proof read `Title:` and `Description:` and ensure they are informative
- [x] Check that all exported functions have `@returns` and `@examples`
- [x] Check that `Authors@R:` includes a copyright holder (role 'cph')
- [x] Review [extrachecks](https://github.com/DavisVaughan/extrachecks)
- [x] `usethis::use_cran_comments()` (optional)

Prepare for release

- [x] Check current CRAN check results
- [x] Check licensing of included files
- [x] Review pkgdown reference index for, e.g., missing topics
- [x] Bump version
- [x] Update `cran-comments.md` (optional)
- [x] Update NEWS.md
- [x] Review pkgdown website
- [ ] `urlchecker::url_check()`
- [ ] Check with local machine
- [ ] Check with GitHub Actions
- [ ] Check with win-builder

Submit to CRAN

- [ ] Draft GitHub release
- [ ] Submit to CRAN via web form
- [ ] Approve emails

Wait for CRAN

- [ ] Accepted :tada:
- [ ] Post on r-packages mailing list
- [ ] Tweet

**Comment by nanxstats** [comment]
forestly 0.1.1 is on CRAN 2024-07-08
