### ISSUE TITLE
Plots are not displayed on the package web site

### ISSUE THREAD

**Issue by fukuhiro2023** [Merck/forestly#65]
Examples of `forestly` plots  are not displayed on the package web site, although those are properly displayed by local build. The attached image is the screen shot of [Get Started](https://merck.github.io/forestly/articles/forestly.html).

![forestly_2024-12-11_GetStarted](https://github.com/user-attachments/assets/8be2b927-3e07-47d9-9f65-0dd743f3a55d)

**Comment by nanxstats** [comment]
I can reproduce this issue locally. The Chrome DevTools console says:

```
react-dom.min.js:79 Uncaught TypeError: Cannot read properties of null (reading 'hasOwnProperty')
    at g (react-tools.js:1:939)
    at u (react-tools.js:1:405)
    at e.map.t.Header (reactable.js:1:127794)
    at reactable.js:1:149873
    at Array.map (<anonymous>)
    at reactable.js:1:149782
    at Array.map (<anonymous>)
    at Ol (reactable.js:1:149584)
    at of (react-dom.min.js:109:301)
    at Rk (react-dom.min.js:250:214)
```

This is likely caused by changes in recent versions of reactR, where reactR <= 0.5.0 still works while it doesn't work starting from reactR 0.6.0, also doesn't work under reactR 0.6.1.
