### ISSUE TITLE
Video does not work on GitHub preview

### ISSUE THREAD

**Issue by nanxstats** [Merck/forestly#7]
The MP4 video embedded in `README.md` currently does not play when previewed on GitHub. By inspecting the network traffic it returns a HTTP 302. It works on the pkgdown site though.

It is possible that GitHub has restrictions on embedding videos/assets from other repos. So I would suggest re-upload the video to a issue in **this** repo and use the new video link.

**Comment by fukuhiro2023** [comment]
The new video based on the recent version has been recorded.
https://github.com/Merck/forestly/assets/129398183/f7257fa9-054b-4c96-afc8-9b3a7b702fa3

**Comment by fukuhiro2023** [comment]
https://github.com/Merck/forestly/assets/129398183/2a645ac6-86f3-42c8-bcba-1970da916fae

**Comment by wangben718** [comment]
Thanks @fukuhiro2023 for updating the video.
